"""Modif id vehicule_retrouve 

Revision ID: 3242ee2239d7
Revises: 45276dded4d7
Create Date: 2024-11-08 14:43:58.687422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3242ee2239d7'
down_revision = '45276dded4d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicule_retrouve',
    sa.Column('vehicule_retrouve_id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('nom_retrouveur', sa.String(length=100), nullable=False),
    sa.Column('prenom_retrouveur', sa.String(length=100), nullable=False),
    sa.Column('num_plaque', sa.String(length=20), nullable=False),
    sa.Column('lieu_long', sa.String(length=100), nullable=False),
    sa.Column('lieu_lat', sa.String(length=100), nullable=False),
    sa.Column('marque', sa.String(length=100), nullable=False),
    sa.Column('modele', sa.String(length=100), nullable=False),
    sa.Column('date_heure', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('vehicule_retrouve_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicule_retrouve')
    # ### end Alembic commands ###
