"""Modif id vehicule_retrouve

Revision ID: 45276dded4d7
Revises: 873aac10cad3
Create Date: 2024-11-08 11:55:13.365945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45276dded4d7'
down_revision = '873aac10cad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicule_retrouve', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicule_retrouve_id', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicule_retrouve', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.drop_column('vehicule_retrouve_id')

    # ### end Alembic commands ###
