"""Initial migration.

Revision ID: 554efe1c8899
Revises: 
Create Date: 2024-06-12 15:17:18.340012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554efe1c8899'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateur',
    sa.Column('utilisateurId', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('adresse', sa.String(length=200), nullable=False),
    sa.Column('telephone', sa.String(length=15), nullable=False),
    sa.Column('motDePasse_hash', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('utilisateurId'),
    sa.UniqueConstraint('email')
    )
    op.create_table('admin',
    sa.Column('adminId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('utilisateurId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['utilisateurId'], ['utilisateur.utilisateurId'], ),
    sa.PrimaryKeyConstraint('adminId'),
    sa.UniqueConstraint('utilisateurId')
    )
    op.create_table('declaration',
    sa.Column('declarationId', sa.Integer(), nullable=False),
    sa.Column('utilisateurId', sa.Integer(), nullable=False),
    sa.Column('nomProprio', sa.String(length=100), nullable=False),
    sa.Column('prenomProprio', sa.String(length=100), nullable=False),
    sa.Column('telephoneProprio', sa.String(length=20), nullable=False),
    sa.Column('lieuLong', sa.String(length=100), nullable=False),
    sa.Column('lieuLat', sa.String(length=100), nullable=False),
    sa.Column('photoCarteGrise', sa.String(length=100), nullable=True),
    sa.Column('numChassis', sa.String(length=100), nullable=False),
    sa.Column('numPlaque', sa.String(length=100), nullable=False),
    sa.Column('marque', sa.String(length=100), nullable=False),
    sa.Column('modele', sa.String(length=100), nullable=False),
    sa.Column('dateHeure', sa.DateTime(), nullable=False),
    sa.Column('statut', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['utilisateurId'], ['utilisateur.utilisateurId'], ),
    sa.PrimaryKeyConstraint('declarationId')
    )
    op.create_table('garage',
    sa.Column('garageId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('utilisateurId', sa.Integer(), nullable=False),
    sa.Column('nomGarage', sa.String(length=100), nullable=False),
    sa.Column('adresseGarage', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['utilisateurId'], ['utilisateur.utilisateurId'], ),
    sa.PrimaryKeyConstraint('garageId'),
    sa.UniqueConstraint('utilisateurId')
    )
    op.create_table('notification',
    sa.Column('notificationId', sa.Integer(), nullable=False),
    sa.Column('utilisateurId', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('dateEnvoi', sa.DateTime(), nullable=True),
    sa.Column('lu', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateurId'], ['utilisateur.utilisateurId'], ),
    sa.PrimaryKeyConstraint('notificationId')
    )
    op.create_table('police',
    sa.Column('policeId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('utilisateurId', sa.Integer(), nullable=False),
    sa.Column('nomDepartement', sa.String(length=100), nullable=False),
    sa.Column('adresseDepartement', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['utilisateurId'], ['utilisateur.utilisateurId'], ),
    sa.PrimaryKeyConstraint('policeId'),
    sa.UniqueConstraint('utilisateurId')
    )
    op.create_table('rdv',
    sa.Column('rdvId', sa.Integer(), nullable=False),
    sa.Column('utilisateurId', sa.Integer(), nullable=False),
    sa.Column('policeId', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('motif', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['policeId'], ['police.policeId'], ),
    sa.ForeignKeyConstraint(['utilisateurId'], ['utilisateur.utilisateurId'], ),
    sa.PrimaryKeyConstraint('rdvId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rdv')
    op.drop_table('police')
    op.drop_table('notification')
    op.drop_table('garage')
    op.drop_table('declaration')
    op.drop_table('admin')
    op.drop_table('utilisateur')
    # ### end Alembic commands ###
