"""Ajout modèle VehiculeRetrouve

Revision ID: 873aac10cad3
Revises: d699c7a40cd4
Create Date: 2024-11-07 22:45:23.532911

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '873aac10cad3'
down_revision = 'd699c7a40cd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicule_retrouve',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('nom_retrouveur', sa.String(length=100), nullable=False),
    sa.Column('prenom_retrouveur', sa.String(length=100), nullable=False),
    sa.Column('num_plaque', sa.String(length=20), nullable=False),
    sa.Column('lieu_long', sa.String(length=100), nullable=False),
    sa.Column('lieu_lat', sa.String(length=100), nullable=False),
    sa.Column('marque', sa.String(length=100), nullable=False),
    sa.Column('modele', sa.String(length=100), nullable=False),
    sa.Column('date_heure', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cache_locks')
    op.drop_table('job_batches')
    op.drop_table('password_reset_tokens')
    op.drop_table('migrations')
    with op.batch_alter_table('failed_jobs', schema=None) as batch_op:
        batch_op.drop_index('failed_jobs_uuid_unique')

    op.drop_table('failed_jobs')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('jobs_queue_index')

    op.drop_table('jobs')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('sessions_last_activity_index')
        batch_op.drop_index('sessions_user_id_index')

    op.drop_table('sessions')
    op.drop_table('cache')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('users_email_unique')

    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email_verified_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('remember_token', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('users_email_unique', ['email'], unique=True)

    op.create_table('cache',
    sa.Column('key', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('value', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('expiration', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sessions',
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('ip_address', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('user_agent', mysql.TEXT(), nullable=True),
    sa.Column('payload', mysql.LONGTEXT(), nullable=False),
    sa.Column('last_activity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('sessions_user_id_index', ['user_id'], unique=False)
        batch_op.create_index('sessions_last_activity_index', ['last_activity'], unique=False)

    op.create_table('jobs',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('queue', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('payload', mysql.LONGTEXT(), nullable=False),
    sa.Column('attempts', mysql.TINYINT(display_width=3, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('reserved_at', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('available_at', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('jobs_queue_index', ['queue'], unique=False)

    op.create_table('failed_jobs',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('uuid', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('connection', mysql.TEXT(), nullable=False),
    sa.Column('queue', mysql.TEXT(), nullable=False),
    sa.Column('payload', mysql.LONGTEXT(), nullable=False),
    sa.Column('exception', mysql.LONGTEXT(), nullable=False),
    sa.Column('failed_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('failed_jobs', schema=None) as batch_op:
        batch_op.create_index('failed_jobs_uuid_unique', ['uuid'], unique=True)

    op.create_table('migrations',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('migration', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('batch', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('password_reset_tokens',
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('token', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('email'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('job_batches',
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('total_jobs', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('pending_jobs', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('failed_jobs', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('failed_job_ids', mysql.LONGTEXT(), nullable=False),
    sa.Column('options', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('cancelled_at', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('finished_at', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('cache_locks',
    sa.Column('key', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('owner', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('expiration', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('vehicule_retrouve')
    # ### end Alembic commands ###
