"""modif de declaration, numplque unique now

Revision ID: 96e8aa02dfb7
Revises: 310e0e102cc0
Create Date: 2024-12-09 14:12:05.299441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96e8aa02dfb7'
down_revision = '310e0e102cc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fcm_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('fcm_token', sa.Text(), nullable=False),
    sa.Column('date_ajout', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('declaration', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['numPlaque'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('declaration', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('fcm_tokens')
    # ### end Alembic commands ###
