"""Ajout du champ Quartier à vehiculeretrouve

Revision ID: 987aa3b12e0a
Revises: 3242ee2239d7
Create Date: 2024-11-25 16:08:01.955668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987aa3b12e0a'
down_revision = '3242ee2239d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicule_retrouve', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quartier', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicule_retrouve', schema=None) as batch_op:
        batch_op.drop_column('quartier')

    # ### end Alembic commands ###
